version: '3' 

services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports: 
      - "443"
    volumes:
      -  wordpress:/var/www/wordpress 
    networks: 
      - inception
  mariadb:
    container_name: mariadb
    networks: 
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose: 
      - "3306"

volumes:
  wordpress:
  mariadb:

networks:
  inception:
      driver: bridge
